KAVACH_MAIN_MODULE_STARTING : "Main module is started"
KAVACH_MAIN_MODULE_ENDED : "Main module ended"
KAVACH_PAUSED : "Login attempts exhausted. System in sleep for 10 seconds."
SYSTEM_RESUMED : "System resumed for use."
REDUCING_LOGIN_ATTEMPTS : "Reducing login attempts due to invalid login."
ENTERIGNG_LOOP : "Entering into loop"
EXITING_LOOP : "Exiting from loop"
VALIDATING_INPUT : "Validating input based on regex."
INVALID_INPUT : "Invalid input entered."
CREATED_REGISTRATION_TABLE : "Successfully Created Users table"
CREATED_KEYS_TABLE : "Successfully Created KEYS table"
CREATED_PASSWORDS_TABLE : "Successfully Created PASSWORDS table"
CREATED_AUDITS_TABLE : "Successfully Created AUDITS table"
DATA_SAVED_DATABASE : "Data Saved to database successfully"
DATA_FETCHED_FROM_DATABASE : "Data fetched database successfully"
