KAVACH_STARTING : "Kavach is starting....."
REGULAR_USER_MENU : |
  You can perform following tasks:
  Press 1 to check strength of any password!!
  Press 2 to generate any strong password !!
  press 3 to Open your passwords dashboard!!
  press 4 Exit!!
ENTER_CHOICE : "Please enter your choice"
PASSWORD_TO_CHECK_STRENGTH : "Enter password whose strength you want to test!! "
LENGTH_FOR_PASSWORD : "Enter length of password you want to create!!"
HI_USER : "Hi {} !!"
PASSWORD_DASHBOARD_MENU : |
  Press 1 to add new password
  Press 2 to see any password
  Press 3 to update password
  Press 4 to delete password
  Press 5 to open audit dashboard
  Press 6 to exit
ENTER_WEBSITE_URL : |
  Enter URL of website whose password you want to save
  if it is not website then press simply enter :
ENTER_PASSWORD : "Enter password: "
ENTER_PASSWORD_TYPE : "Enter password type (eg.login,ATM PIN,Credit card)"
SOMETHING_WENT_WRONG : "Something went wrong please try again!!"
ENTER_PASSWORD_ID_TO_SEE : |
  Enter ID whose encrypted message you want to see 
  other wise just press enter to go back :
ENTER_PASSWORD_ID_TO_UPDATE : |
  Enter ID that ypu want to update 
  other wise just press enter to go back :
ENTER_UPDATED_PASSWORD : "Enter your Updated password!!: "
ENTER_PASSWORD_ID_TO_DELETED : |
  Enter ID that ypu want to update 
  other wise just press enter to go back :
PASSWORD_UPDATED_SUCESSFULLY : "Successfully updated the password"
PASSWORD_DELETED_SUCCESSFULLY : "Successfully deleted the password."
PASSWORD_ADDED_SUCCESSFULLY : "Successfully Added New Password in the KAVACH"

ENTER_USERNAME : "Enter your username :"
ENTER_EMAIL : "Enter your email :"
ENTER_PHONE_NUMBER : "Enter your phone number :"
ENTER_LOGIN_DETAILS : "Please Enter Login Details!!"
LOGIN_OR_REGISTER_CHOICE : |
  If you do not have account then press 1 to create 
  else press any other key to register:

USER_DELETED_SUCCESSFULLY : "{} deleted successfully"
USER_REGISTERED_SUCCESSFULLY : "User registered Successfully!!"
LOGIN_ATTEMPT_LEFT : "You have only {} left!!"
MAXIMUM_ATTEMPT_REACHED : "You have reached the maximum login attempt your screen gut paused for 10 seconds!!"
EXIT_OR_NOT : "Do you want to exit Press y/Y"
SORRY_NO_DATA : "Sorry no data found!!!!"
DUBLICATE_KEY : "Sorry this username is already taken try some else !!!"
AUDIT_MENU : |
  Press 1 to see Fetched audit
  Press 2 to see Updated audit
  Press 3 to Added audit
  Press 4To go back"
ENTER_PASSWORD_ID_TO_FETCH_AUDIT: "Enter Password Id whose Audit you want to see"
INTEGRITY_ERROR_MESSAGE : You entered data that already exist. Please enter unique data
OPERATIONAL_ERROR_MESSAGE : Something unexpected happened with the Database. Please try again after some time
PROGRAMMING_ERROR_MESSAGE : Something wrong with our side. Please wait while we resolve the issue
GENERAL_EXCEPTION_MESSAGE : |
  We are encountering some issue with the system. 
  We will be back soon. 
  Thank you for waiting...
YOU_CANT_DELETE_YOURSELF : "YOU CAN NOT DELETE YOURSELF"


